### PR TITLE
This is for homework 1 & 2

### PR DESCRIPTION
**Pull request by Abubakar-97**
Hello mentors.
I finished with HW 1 & 2. However I do feel I made a mistake where the float for height isn't being displayed

### CODE REVIEW

**Review by Almantask — APPROVED** [review]
Looks good

**Comment by Abubakar-97** [comment]
Dear mentor,

What should I add in this file.

Sincerely,
Memoire

**Comment by Almantask** [comment]
> Dear mentor,
> 
> What should I add in this file.
> 
> Sincerely,
> Memoire

You don't need to reply in a PR like in a letter :D Be more informal, don't worry 👯

**Comment by Almantask** [comment]
You don't neeed to change anything, I forgot to complete it

**Pull request closed without merging**
