### PR TITLE
did the homework for chap 1&2 :>

### PR DESCRIPTION
**Pull request by Pommpeii401**
i think i did this right i may not have tho

:>

### CODE REVIEW

**Comment by Almantask** [comment]
You shouldn't just print hardcoded single-person data. Instead, read it form a console (user input), convert that input to numbers and then perform some math to calculate person's BMI.

**Comment by Pommpeii401** [comment]
Okay got it, will do :>

**Comment by Pommpeii401** [comment]
also just wanted to say your course is really cool and informative

**Comment by Almantask** [comment]
> also just wanted to say your course is really cool and informative

Thanks

**Comment by Pommpeii401** [comment]
@Almantask  did everything 
works now :D

**Review by Almantask — APPROVED** [review]
Looks good, carry on

**Comment by Pommpeii401** [comment]
:DDDDDDDDDDDDDDDD thank uuuuuuuuuuu

**Pull request closed without merging**
