### PR TITLE
Chapter 1 homework 3 complete.

### PR DESCRIPTION
**Pull request by itsjustkevin**
The instructions mention a Lesson3.cs.  That file is not there, easy fix to create it, but instructions may be unclear.

### CODE REVIEW

**Review by Almantask — CHANGES_REQUESTED** [review]
2nd person missing

**Comment by itsjustkevin** [comment]
I am having a little difficulty understanding the instructions, are you asking to calculate the BMI for a second individual?  Are you expecting me to make person instances and pass them into the funcitons?

Or would you like me to just make a SecondDemo member within main?

**Comment by Almantask** [comment]
> I am having a little difficulty understanding the instructions, are you asking to calculate the BMI for a second individual? Are you expecting me to make person instances and pass them into the funcitons?
> 
> Or would you like me to just make a SecondDemo member within main?

Second individual.

**Comment by itsjustkevin** [comment]
The requested change was added.

**Pull request closed without merging**
