### PR TITLE
Chapter1/homework/4

### PR DESCRIPTION
**Pull request by arthur-schevey**
### What I did: 
In all the methods I added conditions to check if the inputs were actually valid. If not they would return an error code (`-1 or -`) as instructed.

The `BmiPrompt()` function then checks for these error codes while executing other code. If the error codes are present, error text will be presented to the user. Otherwise, it will function as normal.

### Issues:
Having significant issues failing checks even though it's seemingly correct in the console. I don't really know what I am doing wrong, the test says that it expected a particular response but received nothing.

Also, I am completely lost on how to return an error code while also returning the original user input. For example user inputs `Age: ffav` --> `"ffav" is not a valid number.`

Currently I get `"-1" is not a valid number.` because the prompt function returns -1 and not the original input.

All I can think of is doing is calling the variable from a prompt function "UserInput" `var UserInput = Console.ReadLine()` from the main class but I am pretty sure this is not possible.

### CODE REVIEW

**Comment by Almantask** [comment]
> Also, I am completely lost on how to return an error code while also returning the original user input. For example user inputs `Age: ffav` --> `"ffav" is not a valid number.`

Printing to a console and returning a value are two different things.
'ffav is not a valid number' is what will be printed, while -1 is what will be returned. 😄

**Comment by Almantask** [comment]
> > Also, I am completely lost on how to return an error code while also returning the original user input. For example user inputs `Age: ffav` --> `"ffav" is not a valid number.`
> 
> Printing to a console and returning a value are two different things.
> 'ffav is not a valid number' is what will be printed, while -1 is what will be returned. 😄

So print to console from the function itself, not outside of it.

**Comment by arthur-schevey** [comment]
> 
> 
> > Also, I am completely lost on how to return an error code while also returning the original user input. For example user inputs `Age: ffav` --> `"ffav" is not a valid number.`
> 
> Printing to a console and returning a value are two different things.
> 'ffav is not a valid number' is what will be printed, while -1 is what will be returned. 😄

I'm such a fool, you're such a genius. Thank you so much, I don't know why my brain completely blocked me out from doing that.

I still seem to be failing checks even though I believe it's correct in console. Is there something I have done wrong?

**Comment by Almantask** [comment]
> > > Also, I am completely lost on how to return an error code while also returning the original user input. For example user inputs `Age: ffav` --> `"ffav" is not a valid number.`
> > 
> > 
> > Printing to a console and returning a value are two different things.
> > 'ffav is not a valid number' is what will be printed, while -1 is what will be returned. 😄
> 
> I'm such a fool, you're such a genius. Thank you so much, I don't know why my brain completely blocked me out from doing that.
> 
> I still seem to be failing checks even though I believe it's correct in console. Is there something I have done wrong?

Yup, error messages are all wrong. Sometimes you don't print it at all, sometimes you do WrtieLine where Write is needed, etc. Be more careful the way you do it.

**Comment by Almantask** [comment]
> > > > Also, I am completely lost on how to return an error code while also returning the original user input. For example user inputs `Age: ffav` --> `"ffav" is not a valid number.`
> > > 
> > > 
> > > Printing to a console and returning a value are two different things.
> > > 'ffav is not a valid number' is what will be printed, while -1 is what will be returned. 😄
> > 
> > 
> > I'm such a fool, you're such a genius. Thank you so much, I don't know why my brain completely blocked me out from doing that.
> > I still seem to be failing checks even though I believe it's correct in console. Is there something I have done wrong?
> 
> Yup, error messages are all wrong. Sometimes you don't print it at all, sometimes you do WrtieLine where Write is needed, etc. Be more careful the way you do it.

You can see all the reasons why it failed if you click the checks link.

**Comment by Almantask** [comment]
Expired

**Pull request closed without merging**
